
  - name: install mysql libraries PyMySQL 3.9
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop: 
    - cryptography
    - PyMySQL

  - name: installing mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql-server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Set MySQL root password using mysql_user
    community.mysql.mysql_user:
      name: root
      host: localhost
      password: "{{ mysql_root_password }}"
      login_unix_socket: /var/lib/mysql/mysql.sock
      state: present



  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "ExpenseApp@1"
      login_host: "{{ mysql_host }}"
    register: mysql_info
    ignore_errors: true
      
  - name: print the output
    ansible.builtin.debug:
      msg: "mysql info {{ mysql_info }}"

